site_name: huchaoning/hcn Documentation
repo_url: https://github.com/huchaoning/hcn

theme:
  name: material
  language: en
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - content.code.copy

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings

nav:
  - Home: index.md
  - hcn.preamble: preamble.ipynb
  - hcn.io: io.md
  - hcn.utils: utils.md
