site_name: huchaoning/hcn Documentation
repo_url: https://github.com/huchaoning/hcn
copyright: Copyright (c) 2023 <a href="https://github.com/huchaoning">Chao-Ning Hu</a>


theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true


plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      execute: true 
      include_requirejs: true
      kernel_name: python3
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
      ignore_h1_titles: true


nav:
  - Home: index.ipynb
  - Preamble setup: preamble.ipynb
  - Data I/O: io.ipynb
  - General Utilities: 
      cache: cache.ipynb
      parallelize: parallelize.ipynb
